<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
		<link REL="stylesheet" TYPE="text/css" href="_stylesheet_">
		<title>
			_title_
		</title>
	</head>
	
	<body>

	<div class="logo">
		<h3>clcms 0.6 documentation</h3>
	</div>

	<div id="main">

	_menu_1_

	<div class="menu1_contents">

	_menu2_
	<div class="datablock">

	<div class="updated">
		PageNav:<br />
		Next: _nextpage_<br />
		Up: _uppage_<br />
		Prev: _prevpage_<br />
	</div>

	_submenu_

	<div class="updated">
		<a href="http://jelte.nlnetlabs.nl/Projects/clcms/index.html">To Project Page</a>
	</div>

	<div class="updated">
		Last updated:<br />
		_datefile_
	</div>

	</div>

