									</div>
									<hr class="hide">

								</div>
								<div class="clear"></div>
							</div>
						</div>
					</div>
					<div id="leftColumn">
						<div class="inside">

						_menu_(2)_

						<hr class="hide">
						</div>
					</div>
					<div id="footer">

					<p>
					Last Updated: _datefile_
					</p>

					<hr class="hide">
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>

	</body>

</html>
