									</div>
									<hr class="hide">

								</div>
								<div class="clear"></div>
							</div>
						</div>
					</div>
					<div id="leftColumn">
						<div class="inside">

							<div id="cornerLogo">
								<div class="placeHolder">
									<p>
										Your logo goes here.
									</p>
								</div>
							</div>

							<hr class="hide">
						</div>
					</div>
					<div id="footer">

						<p>
							Last Updated: _datefile_
						</p>
						<hr class="hide">
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>

	</body>

</html>
